---
title: "2021 NCAA Tournament Predictions"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(DT)
setwd("C:/Users/mtdic/Documents/GitHub/march-ml-mania-21/data/men/")
sub <- read.csv("subs/submission_probs_trimmed_2021-03-17.csv")
sub$TeamID_1 <- as.integer(substr(sub$ID, 6, 9))
sub$TeamID_2 <- as.integer(substr(sub$ID, 11, 14))
teams <- read.csv("MTeams.csv")

names(teams) <- c("TeamID_1", "TeamName_1", "fd1_1", "ld1_1")
sub <- merge(sub, teams[,1:2], by = "TeamID_1")
names(teams) <- c("TeamID_2", "TeamName_2", "fd1_2", "ld1_2")
sub <- merge(sub, teams[,1:2], by = "TeamID_2")

```

### Trimmed Probabilities Submitted to Kaggle

Probabilities are truncated at 95% (or below 5%) to protect from severe log-loss penalty.

```{r cars, echo = FALSE}

sub$Pred_percent_rounded <- round(sub$Pred*100, 2)

datatable(sub[,c("ID", "TeamName_1", "TeamName_2", "Pred_percent_rounded")], filter = "top", options = list(pageLength = 20))
```